# Generated by Django 3.1 on 2020-08-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_auto_20200826_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='TripFrom',
            new_name='tripfrom',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='TripTo',
            new_name='tripto',
        ),
    ]
