# Generated by Django 3.1 on 2020-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_auto_20200826_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
