# Generated by Django 3.1 on 2020-08-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0007_auto_20200826_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=50)),
                ('orno', models.CharField(max_length=20)),
                ('crno', models.CharField(max_length=20)),
            ],
        ),
    ]
