# Generated by Django 3.1 on 2020-08-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0008_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='queue',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='members',
            name='area',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='crno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='mname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='orno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='plate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
