# Generated by Django 3.1 on 2020-08-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0009_auto_20200827_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
