# Generated by Django 3.1 on 2020-08-27 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0011_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(default='', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sacrifice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TripsBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(default='', max_length=3)),
                ('r1', models.BooleanField()),
                ('r2', models.BooleanField()),
                ('r3', models.BooleanField()),
                ('r4', models.BooleanField()),
                ('r5', models.BooleanField()),
            ],
        ),
    ]
