# Generated by Django 3.1 on 2020-08-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0012_trips_tripsboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripsBoard',
            new_name='TripBoard',
        ),
    ]
