# Generated by Django 3.1 on 2020-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0013_auto_20200827_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripboard',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
