# Generated by Django 3.1 on 2020-08-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0014_tripboard_lname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripBoard',
        ),
    ]
