# Generated by Django 3.1 on 2020-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0015_delete_tripboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(default='', max_length=3)),
                ('lname', models.CharField(default='', max_length=100)),
                ('r1', models.BooleanField()),
                ('r2', models.BooleanField()),
                ('r3', models.BooleanField()),
                ('r4', models.BooleanField()),
                ('r5', models.BooleanField()),
            ],
        ),
    ]
