# Generated by Django 3.1 on 2020-08-27 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0016_tripboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(default='', max_length=100)),
                ('plate', models.CharField(default='', max_length=10)),
                ('valid', models.BooleanField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
