# Generated by Django 3.1 on 2020-08-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0017_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='valid',
            field=models.IntegerField(),
        ),
    ]
